import React from 'react'

import Head from 'next/head'
import Link from 'next/link'
import Router from 'next/router'
import Image from 'next/image'

import { Formik, Field, Form } from 'formik'
import _ from 'lodash'

/* ====================================================== */
/*                         Hooks                          */
/* ====================================================== */

import { useSelector, useDispatch } from 'react-redux'

/* ====================================================== */
/*                   Actions / Selectors                  */
/* ====================================================== */

import { addStreamer, removeStreamer, resetList } from 'Redux/actions'

/* ====================================================== */
/*                       Components                       */
/* ====================================================== */

import Layout from 'Components/layout/layout'

/* ====================================================== */
/*                         Styles                         */
/* ====================================================== */

import styles from 'Styles/Home.module.css'

/* ====================================================== */
/*                    Implementation                      */
/* ====================================================== */

export default function Home() {
	const dispatch = useDispatch()

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <Script
        src="https://connect.facebook.net/en_US/sdk.js"
        strategy="lazyOnload"
        onLoad={() =>
          console.log(`script loaded correctly, window.FB has been populated`)
        }
      /> */}
			<Layout>
				<main className={styles.main}>
					<h1>Type the name of your streamer and go watch it</h1>
					<Formik
						initialValues={{
							streamerName: '',
						}}
						onSubmit={async (values, { resetForm }) => {
							const { streamerName } = values
							dispatch(addStreamer(streamerName))
							Router.push('/twitch')
						}}
					>
						<Form>
							<label htmlFor="streamerName">Streamer</label>
							<Field id="streamerName" name="streamerName" placeholder="Twitch channel" />

							<button type="submit">Submit</button>
						</Form>
					</Formik>
				</main>
			</Layout>
		</div>
	)
}
